version: "3.5"
networks:
    default:
      external:
        name: setup_default

services:
    first-join:
        image: stream-transformer
        environment: 
            LEFT_TOPIC: CIMSTEST.Financial.ClaimStatusClaimLink
            RIGHT_TOPIC: CIMSTEST.Financial.ClaimStatus
            OUTPUT_TOPIC: ClaimStatusClaimLink_ClaimStatus
            COMMON_KEY: CS_ClaimStatusID
            BROKER: broker:9092
            SCHEMA_REGISTRY: http://schema-registry:8081
            APPLICATION_ID: first-join
            AUTO_OFFSET_RESET_CONFIG: earliest
    second-join:
        image: stream-transformer
        environment: 
            LEFT_TOPIC: CIMSTEST.Financial.ClaimNoteLink
            RIGHT_TOPIC: CIMSTEST.Financial.ClaimVoucherNoteClaimLink
            OUTPUT_TOPIC: ClaimNoteLink_ClaimVoucherNoteClaimLink
            COMMON_KEY: CL_ClaimID
            BROKER: broker:9092
            SCHEMA_REGISTRY: http://schema-registry:8081
            APPLICATION_ID: second-join
            AUTO_OFFSET_RESET_CONFIG: earliest
    thrid-join:
        image: stream-transformer
        environment: 
            LEFT_TOPIC: ClaimStatusClaimLink_ClaimStatus
            RIGHT_TOPIC: ClaimNoteLink_ClaimVoucherNoteClaimLink
            OUTPUT_TOPIC: ClaimStatusClaimLink_ClaimStatus_ClaimNoteLink_ClaimVoucherNoteClaimLink
            COMMON_KEY: CL_ClaimID
            BROKER: broker:9092
            SCHEMA_REGISTRY: http://schema-registry:8081
            APPLICATION_ID: third-join
            AUTO_OFFSET_RESET_CONFIG: earliest
    fourth-join:
        image: stream-transformer
        environment: 
            LEFT_TOPIC: ClaimStatusClaimLink_ClaimStatus
            RIGHT_TOPIC: CIMSTEST.Financial.ClaimVoucherNoteClaimLink
            OUTPUT_TOPIC: ClaimStatusClaimLink_ClaimStatus_ClaimVoucherNoteClaimLink
            COMMON_KEY: CL_ClaimID
            BROKER: broker:9092
            SCHEMA_REGISTRY: http://schema-registry:8081
            APPLICATION_ID: fourth-join
            AUTO_OFFSET_RESET_CONFIG: earliest