/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gms.cims.bridge;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClaimStatus_ClaimStatusClaimLink_ClaimContractLink extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8377191767427623169L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClaimStatus_ClaimStatusClaimLink_ClaimContractLink\",\"namespace\":\"gms.cims.bridge\",\"fields\":[{\"name\":\"CL_ClaimID\",\"type\":[\"int\",\"null\"],\"default\":-1},{\"name\":\"CS_ClaimStatusID\",\"type\":[\"int\",\"null\"],\"default\":-1},{\"name\":\"CS_Description\",\"type\":[\"string\",\"null\"],\"default\":\"NONE\"},{\"name\":\"CC_Relationship\",\"type\":[\"int\",\"null\"],\"default\":-1},{\"name\":\"CO_ContractID\",\"type\":[\"int\",\"null\"],\"default\":-1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink> ENCODER =
      new BinaryMessageEncoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink> DECODER =
      new BinaryMessageDecoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClaimStatus_ClaimStatusClaimLink_ClaimContractLink to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClaimStatus_ClaimStatusClaimLink_ClaimContractLink from a ByteBuffer. */
  public static ClaimStatus_ClaimStatusClaimLink_ClaimContractLink fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer CL_ClaimID;
  @Deprecated public java.lang.Integer CS_ClaimStatusID;
  @Deprecated public java.lang.CharSequence CS_Description;
  @Deprecated public java.lang.Integer CC_Relationship;
  @Deprecated public java.lang.Integer CO_ContractID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClaimStatus_ClaimStatusClaimLink_ClaimContractLink() {}

  /**
   * All-args constructor.
   * @param CL_ClaimID The new value for CL_ClaimID
   * @param CS_ClaimStatusID The new value for CS_ClaimStatusID
   * @param CS_Description The new value for CS_Description
   * @param CC_Relationship The new value for CC_Relationship
   * @param CO_ContractID The new value for CO_ContractID
   */
  public ClaimStatus_ClaimStatusClaimLink_ClaimContractLink(java.lang.Integer CL_ClaimID, java.lang.Integer CS_ClaimStatusID, java.lang.CharSequence CS_Description, java.lang.Integer CC_Relationship, java.lang.Integer CO_ContractID) {
    this.CL_ClaimID = CL_ClaimID;
    this.CS_ClaimStatusID = CS_ClaimStatusID;
    this.CS_Description = CS_Description;
    this.CC_Relationship = CC_Relationship;
    this.CO_ContractID = CO_ContractID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CL_ClaimID;
    case 1: return CS_ClaimStatusID;
    case 2: return CS_Description;
    case 3: return CC_Relationship;
    case 4: return CO_ContractID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CL_ClaimID = (java.lang.Integer)value$; break;
    case 1: CS_ClaimStatusID = (java.lang.Integer)value$; break;
    case 2: CS_Description = (java.lang.CharSequence)value$; break;
    case 3: CC_Relationship = (java.lang.Integer)value$; break;
    case 4: CO_ContractID = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CL_ClaimID' field.
   * @return The value of the 'CL_ClaimID' field.
   */
  public java.lang.Integer getCLClaimID() {
    return CL_ClaimID;
  }

  /**
   * Sets the value of the 'CL_ClaimID' field.
   * @param value the value to set.
   */
  public void setCLClaimID(java.lang.Integer value) {
    this.CL_ClaimID = value;
  }

  /**
   * Gets the value of the 'CS_ClaimStatusID' field.
   * @return The value of the 'CS_ClaimStatusID' field.
   */
  public java.lang.Integer getCSClaimStatusID() {
    return CS_ClaimStatusID;
  }

  /**
   * Sets the value of the 'CS_ClaimStatusID' field.
   * @param value the value to set.
   */
  public void setCSClaimStatusID(java.lang.Integer value) {
    this.CS_ClaimStatusID = value;
  }

  /**
   * Gets the value of the 'CS_Description' field.
   * @return The value of the 'CS_Description' field.
   */
  public java.lang.CharSequence getCSDescription() {
    return CS_Description;
  }

  /**
   * Sets the value of the 'CS_Description' field.
   * @param value the value to set.
   */
  public void setCSDescription(java.lang.CharSequence value) {
    this.CS_Description = value;
  }

  /**
   * Gets the value of the 'CC_Relationship' field.
   * @return The value of the 'CC_Relationship' field.
   */
  public java.lang.Integer getCCRelationship() {
    return CC_Relationship;
  }

  /**
   * Sets the value of the 'CC_Relationship' field.
   * @param value the value to set.
   */
  public void setCCRelationship(java.lang.Integer value) {
    this.CC_Relationship = value;
  }

  /**
   * Gets the value of the 'CO_ContractID' field.
   * @return The value of the 'CO_ContractID' field.
   */
  public java.lang.Integer getCOContractID() {
    return CO_ContractID;
  }

  /**
   * Sets the value of the 'CO_ContractID' field.
   * @param value the value to set.
   */
  public void setCOContractID(java.lang.Integer value) {
    this.CO_ContractID = value;
  }

  /**
   * Creates a new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder.
   * @return A new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder newBuilder() {
    return new gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder();
  }

  /**
   * Creates a new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder newBuilder(gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder other) {
    return new gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder(other);
  }

  /**
   * Creates a new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder by copying an existing ClaimStatus_ClaimStatusClaimLink_ClaimContractLink instance.
   * @param other The existing instance to copy.
   * @return A new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder newBuilder(gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink other) {
    return new gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder(other);
  }

  /**
   * RecordBuilder for ClaimStatus_ClaimStatusClaimLink_ClaimContractLink instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>
    implements org.apache.avro.data.RecordBuilder<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink> {

    private java.lang.Integer CL_ClaimID;
    private java.lang.Integer CS_ClaimStatusID;
    private java.lang.CharSequence CS_Description;
    private java.lang.Integer CC_Relationship;
    private java.lang.Integer CO_ContractID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[0].schema(), other.CL_ClaimID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CS_ClaimStatusID)) {
        this.CS_ClaimStatusID = data().deepCopy(fields()[1].schema(), other.CS_ClaimStatusID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[2].schema(), other.CS_Description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CC_Relationship)) {
        this.CC_Relationship = data().deepCopy(fields()[3].schema(), other.CC_Relationship);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[4].schema(), other.CO_ContractID);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClaimStatus_ClaimStatusClaimLink_ClaimContractLink instance
     * @param other The existing instance to copy.
     */
    private Builder(gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[0].schema(), other.CL_ClaimID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CS_ClaimStatusID)) {
        this.CS_ClaimStatusID = data().deepCopy(fields()[1].schema(), other.CS_ClaimStatusID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[2].schema(), other.CS_Description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CC_Relationship)) {
        this.CC_Relationship = data().deepCopy(fields()[3].schema(), other.CC_Relationship);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[4].schema(), other.CO_ContractID);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'CL_ClaimID' field.
      * @return The value.
      */
    public java.lang.Integer getCLClaimID() {
      return CL_ClaimID;
    }

    /**
      * Sets the value of the 'CL_ClaimID' field.
      * @param value The value of 'CL_ClaimID'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder setCLClaimID(java.lang.Integer value) {
      validate(fields()[0], value);
      this.CL_ClaimID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_ClaimID' field has been set.
      * @return True if the 'CL_ClaimID' field has been set, false otherwise.
      */
    public boolean hasCLClaimID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CL_ClaimID' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder clearCLClaimID() {
      CL_ClaimID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CS_ClaimStatusID' field.
      * @return The value.
      */
    public java.lang.Integer getCSClaimStatusID() {
      return CS_ClaimStatusID;
    }

    /**
      * Sets the value of the 'CS_ClaimStatusID' field.
      * @param value The value of 'CS_ClaimStatusID'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder setCSClaimStatusID(java.lang.Integer value) {
      validate(fields()[1], value);
      this.CS_ClaimStatusID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CS_ClaimStatusID' field has been set.
      * @return True if the 'CS_ClaimStatusID' field has been set, false otherwise.
      */
    public boolean hasCSClaimStatusID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CS_ClaimStatusID' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder clearCSClaimStatusID() {
      CS_ClaimStatusID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'CS_Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getCSDescription() {
      return CS_Description;
    }

    /**
      * Sets the value of the 'CS_Description' field.
      * @param value The value of 'CS_Description'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder setCSDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.CS_Description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'CS_Description' field has been set.
      * @return True if the 'CS_Description' field has been set, false otherwise.
      */
    public boolean hasCSDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'CS_Description' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder clearCSDescription() {
      CS_Description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CC_Relationship' field.
      * @return The value.
      */
    public java.lang.Integer getCCRelationship() {
      return CC_Relationship;
    }

    /**
      * Sets the value of the 'CC_Relationship' field.
      * @param value The value of 'CC_Relationship'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder setCCRelationship(java.lang.Integer value) {
      validate(fields()[3], value);
      this.CC_Relationship = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CC_Relationship' field has been set.
      * @return True if the 'CC_Relationship' field has been set, false otherwise.
      */
    public boolean hasCCRelationship() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CC_Relationship' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder clearCCRelationship() {
      CC_Relationship = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CO_ContractID' field.
      * @return The value.
      */
    public java.lang.Integer getCOContractID() {
      return CO_ContractID;
    }

    /**
      * Sets the value of the 'CO_ContractID' field.
      * @param value The value of 'CO_ContractID'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder setCOContractID(java.lang.Integer value) {
      validate(fields()[4], value);
      this.CO_ContractID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CO_ContractID' field has been set.
      * @return True if the 'CO_ContractID' field has been set, false otherwise.
      */
    public boolean hasCOContractID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CO_ContractID' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus_ClaimStatusClaimLink_ClaimContractLink.Builder clearCOContractID() {
      CO_ContractID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClaimStatus_ClaimStatusClaimLink_ClaimContractLink build() {
      try {
        ClaimStatus_ClaimStatusClaimLink_ClaimContractLink record = new ClaimStatus_ClaimStatusClaimLink_ClaimContractLink();
        record.CL_ClaimID = fieldSetFlags()[0] ? this.CL_ClaimID : (java.lang.Integer) defaultValue(fields()[0]);
        record.CS_ClaimStatusID = fieldSetFlags()[1] ? this.CS_ClaimStatusID : (java.lang.Integer) defaultValue(fields()[1]);
        record.CS_Description = fieldSetFlags()[2] ? this.CS_Description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CC_Relationship = fieldSetFlags()[3] ? this.CC_Relationship : (java.lang.Integer) defaultValue(fields()[3]);
        record.CO_ContractID = fieldSetFlags()[4] ? this.CO_ContractID : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>
    READER$ = (org.apache.avro.io.DatumReader<ClaimStatus_ClaimStatusClaimLink_ClaimContractLink>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
