version: "3.5"
networks:
    default:
      external:
        name: setup_default

services:
  join1:
    image: stream-transformer-specific-2.0
    environment:
      BROKER: http://broker:29092
      SCHEMA_REGISTRY: http://schema-registry:8081
      OUTPUT_TOPIC: join
      AUTO_OFFSET_RESET_CONFIG: earliest
  join2:
    image: stream-transformer-specific-2.0
    environment:
      BROKER: http://broker:29092
      SCHEMA_REGISTRY: http://schema-registry:8081
      OUTPUT_TOPIC: join
      AUTO_OFFSET_RESET_CONFIG: earliest
  join3:
    image: stream-transformer-specific-2.0
    environment:
      BROKER: http://broker:29092
      SCHEMA_REGISTRY: http://schema-registry:8081
      OUTPUT_TOPIC: join
      AUTO_OFFSET_RESET_CONFIG: earliest
  join4:
    image: stream-transformer-specific-2.0
    environment:
      BROKER: http://broker:29092
      SCHEMA_REGISTRY: http://schema-registry:8081
      OUTPUT_TOPIC: join
      AUTO_OFFSET_RESET_CONFIG: earliest