/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.gms.claimclasses;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClaimContractLink_ClaimContractRelationships extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1806948805857498368L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClaimContractLink_ClaimContractRelationships\",\"namespace\":\"org.gms.claimclasses\",\"fields\":[{\"name\":\"CC_Description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CL_ClaimID\",\"type\":\"int\"},{\"name\":\"CO_ContractID\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClaimContractLink_ClaimContractRelationships> ENCODER =
      new BinaryMessageEncoder<ClaimContractLink_ClaimContractRelationships>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClaimContractLink_ClaimContractRelationships> DECODER =
      new BinaryMessageDecoder<ClaimContractLink_ClaimContractRelationships>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClaimContractLink_ClaimContractRelationships> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClaimContractLink_ClaimContractRelationships> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClaimContractLink_ClaimContractRelationships>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClaimContractLink_ClaimContractRelationships to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClaimContractLink_ClaimContractRelationships from a ByteBuffer. */
  public static ClaimContractLink_ClaimContractRelationships fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence CC_Description;
  @Deprecated public int CL_ClaimID;
  @Deprecated public java.lang.Integer CO_ContractID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClaimContractLink_ClaimContractRelationships() {}

  /**
   * All-args constructor.
   * @param CC_Description The new value for CC_Description
   * @param CL_ClaimID The new value for CL_ClaimID
   * @param CO_ContractID The new value for CO_ContractID
   */
  public ClaimContractLink_ClaimContractRelationships(java.lang.CharSequence CC_Description, java.lang.Integer CL_ClaimID, java.lang.Integer CO_ContractID) {
    this.CC_Description = CC_Description;
    this.CL_ClaimID = CL_ClaimID;
    this.CO_ContractID = CO_ContractID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CC_Description;
    case 1: return CL_ClaimID;
    case 2: return CO_ContractID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CC_Description = (java.lang.CharSequence)value$; break;
    case 1: CL_ClaimID = (java.lang.Integer)value$; break;
    case 2: CO_ContractID = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CC_Description' field.
   * @return The value of the 'CC_Description' field.
   */
  public java.lang.CharSequence getCCDescription() {
    return CC_Description;
  }

  /**
   * Sets the value of the 'CC_Description' field.
   * @param value the value to set.
   */
  public void setCCDescription(java.lang.CharSequence value) {
    this.CC_Description = value;
  }

  /**
   * Gets the value of the 'CL_ClaimID' field.
   * @return The value of the 'CL_ClaimID' field.
   */
  public java.lang.Integer getCLClaimID() {
    return CL_ClaimID;
  }

  /**
   * Sets the value of the 'CL_ClaimID' field.
   * @param value the value to set.
   */
  public void setCLClaimID(java.lang.Integer value) {
    this.CL_ClaimID = value;
  }

  /**
   * Gets the value of the 'CO_ContractID' field.
   * @return The value of the 'CO_ContractID' field.
   */
  public java.lang.Integer getCOContractID() {
    return CO_ContractID;
  }

  /**
   * Sets the value of the 'CO_ContractID' field.
   * @param value the value to set.
   */
  public void setCOContractID(java.lang.Integer value) {
    this.CO_ContractID = value;
  }

  /**
   * Creates a new ClaimContractLink_ClaimContractRelationships RecordBuilder.
   * @return A new ClaimContractLink_ClaimContractRelationships RecordBuilder
   */
  public static org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder newBuilder() {
    return new org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder();
  }

  /**
   * Creates a new ClaimContractLink_ClaimContractRelationships RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClaimContractLink_ClaimContractRelationships RecordBuilder
   */
  public static org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder newBuilder(org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder other) {
    return new org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder(other);
  }

  /**
   * Creates a new ClaimContractLink_ClaimContractRelationships RecordBuilder by copying an existing ClaimContractLink_ClaimContractRelationships instance.
   * @param other The existing instance to copy.
   * @return A new ClaimContractLink_ClaimContractRelationships RecordBuilder
   */
  public static org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder newBuilder(org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships other) {
    return new org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder(other);
  }

  /**
   * RecordBuilder for ClaimContractLink_ClaimContractRelationships instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClaimContractLink_ClaimContractRelationships>
    implements org.apache.avro.data.RecordBuilder<ClaimContractLink_ClaimContractRelationships> {

    private java.lang.CharSequence CC_Description;
    private int CL_ClaimID;
    private java.lang.Integer CO_ContractID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CC_Description)) {
        this.CC_Description = data().deepCopy(fields()[0].schema(), other.CC_Description);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[1].schema(), other.CL_ClaimID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[2].schema(), other.CO_ContractID);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClaimContractLink_ClaimContractRelationships instance
     * @param other The existing instance to copy.
     */
    private Builder(org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CC_Description)) {
        this.CC_Description = data().deepCopy(fields()[0].schema(), other.CC_Description);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[1].schema(), other.CL_ClaimID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[2].schema(), other.CO_ContractID);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'CC_Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getCCDescription() {
      return CC_Description;
    }

    /**
      * Sets the value of the 'CC_Description' field.
      * @param value The value of 'CC_Description'.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder setCCDescription(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CC_Description = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CC_Description' field has been set.
      * @return True if the 'CC_Description' field has been set, false otherwise.
      */
    public boolean hasCCDescription() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CC_Description' field.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder clearCCDescription() {
      CC_Description = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CL_ClaimID' field.
      * @return The value.
      */
    public java.lang.Integer getCLClaimID() {
      return CL_ClaimID;
    }

    /**
      * Sets the value of the 'CL_ClaimID' field.
      * @param value The value of 'CL_ClaimID'.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder setCLClaimID(int value) {
      validate(fields()[1], value);
      this.CL_ClaimID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_ClaimID' field has been set.
      * @return True if the 'CL_ClaimID' field has been set, false otherwise.
      */
    public boolean hasCLClaimID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CL_ClaimID' field.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder clearCLClaimID() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'CO_ContractID' field.
      * @return The value.
      */
    public java.lang.Integer getCOContractID() {
      return CO_ContractID;
    }

    /**
      * Sets the value of the 'CO_ContractID' field.
      * @param value The value of 'CO_ContractID'.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder setCOContractID(java.lang.Integer value) {
      validate(fields()[2], value);
      this.CO_ContractID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'CO_ContractID' field has been set.
      * @return True if the 'CO_ContractID' field has been set, false otherwise.
      */
    public boolean hasCOContractID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'CO_ContractID' field.
      * @return This builder.
      */
    public org.gms.claimclasses.ClaimContractLink_ClaimContractRelationships.Builder clearCOContractID() {
      CO_ContractID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClaimContractLink_ClaimContractRelationships build() {
      try {
        ClaimContractLink_ClaimContractRelationships record = new ClaimContractLink_ClaimContractRelationships();
        record.CC_Description = fieldSetFlags()[0] ? this.CC_Description : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CL_ClaimID = fieldSetFlags()[1] ? this.CL_ClaimID : (java.lang.Integer) defaultValue(fields()[1]);
        record.CO_ContractID = fieldSetFlags()[2] ? this.CO_ContractID : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClaimContractLink_ClaimContractRelationships>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClaimContractLink_ClaimContractRelationships>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClaimContractLink_ClaimContractRelationships>
    READER$ = (org.apache.avro.io.DatumReader<ClaimContractLink_ClaimContractRelationships>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
