/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.gms.claimclasses;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Claim_ClaimStatus_ClaimStatusClaimLink extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 952142203728324525L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Claim_ClaimStatus_ClaimStatusClaimLink\",\"namespace\":\"org.gms.claimclasses\",\"fields\":[{\"name\":\"CL_ClaimID\",\"type\":\"int\"},{\"name\":\"CL_FeeSubmitted\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"CL_TotalOwed\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"CL_Paid\",\"type\":\"boolean\"},{\"name\":\"CS_Description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CL_ProcessDate\",\"type\":{\"type\":\"int\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.Date\"}},{\"name\":\"CB_ClaimStateID\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Claim_ClaimStatus_ClaimStatusClaimLink> ENCODER =
      new BinaryMessageEncoder<Claim_ClaimStatus_ClaimStatusClaimLink>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Claim_ClaimStatus_ClaimStatusClaimLink> DECODER =
      new BinaryMessageDecoder<Claim_ClaimStatus_ClaimStatusClaimLink>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Claim_ClaimStatus_ClaimStatusClaimLink> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Claim_ClaimStatus_ClaimStatusClaimLink> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Claim_ClaimStatus_ClaimStatusClaimLink>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Claim_ClaimStatus_ClaimStatusClaimLink to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Claim_ClaimStatus_ClaimStatusClaimLink from a ByteBuffer. */
  public static Claim_ClaimStatus_ClaimStatusClaimLink fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int CL_ClaimID;
  @Deprecated public java.lang.Double CL_FeeSubmitted;
  @Deprecated public java.lang.Double CL_TotalOwed;
  @Deprecated public boolean CL_Paid;
  @Deprecated public java.lang.CharSequence CS_Description;
  @Deprecated public int CL_ProcessDate;
  @Deprecated public java.lang.Integer CB_ClaimStateID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Claim_ClaimStatus_ClaimStatusClaimLink() {}

  /**
   * All-args constructor.
   * @param CL_ClaimID The new value for CL_ClaimID
   * @param CL_FeeSubmitted The new value for CL_FeeSubmitted
   * @param CL_TotalOwed The new value for CL_TotalOwed
   * @param CL_Paid The new value for CL_Paid
   * @param CS_Description The new value for CS_Description
   * @param CL_ProcessDate The new value for CL_ProcessDate
   * @param CB_ClaimStateID The new value for CB_ClaimStateID
   */
  public Claim_ClaimStatus_ClaimStatusClaimLink(java.lang.Integer CL_ClaimID, java.lang.Double CL_FeeSubmitted, java.lang.Double CL_TotalOwed, java.lang.Boolean CL_Paid, java.lang.CharSequence CS_Description, java.lang.Integer CL_ProcessDate, java.lang.Integer CB_ClaimStateID) {
    this.CL_ClaimID = CL_ClaimID;
    this.CL_FeeSubmitted = CL_FeeSubmitted;
    this.CL_TotalOwed = CL_TotalOwed;
    this.CL_Paid = CL_Paid;
    this.CS_Description = CS_Description;
    this.CL_ProcessDate = CL_ProcessDate;
    this.CB_ClaimStateID = CB_ClaimStateID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CL_ClaimID;
    case 1: return CL_FeeSubmitted;
    case 2: return CL_TotalOwed;
    case 3: return CL_Paid;
    case 4: return CS_Description;
    case 5: return CL_ProcessDate;
    case 6: return CB_ClaimStateID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CL_ClaimID = (java.lang.Integer)value$; break;
    case 1: CL_FeeSubmitted = (java.lang.Double)value$; break;
    case 2: CL_TotalOwed = (java.lang.Double)value$; break;
    case 3: CL_Paid = (java.lang.Boolean)value$; break;
    case 4: CS_Description = (java.lang.CharSequence)value$; break;
    case 5: CL_ProcessDate = (java.lang.Integer)value$; break;
    case 6: CB_ClaimStateID = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CL_ClaimID' field.
   * @return The value of the 'CL_ClaimID' field.
   */
  public java.lang.Integer getCLClaimID() {
    return CL_ClaimID;
  }

  /**
   * Sets the value of the 'CL_ClaimID' field.
   * @param value the value to set.
   */
  public void setCLClaimID(java.lang.Integer value) {
    this.CL_ClaimID = value;
  }

  /**
   * Gets the value of the 'CL_FeeSubmitted' field.
   * @return The value of the 'CL_FeeSubmitted' field.
   */
  public java.lang.Double getCLFeeSubmitted() {
    return CL_FeeSubmitted;
  }

  /**
   * Sets the value of the 'CL_FeeSubmitted' field.
   * @param value the value to set.
   */
  public void setCLFeeSubmitted(java.lang.Double value) {
    this.CL_FeeSubmitted = value;
  }

  /**
   * Gets the value of the 'CL_TotalOwed' field.
   * @return The value of the 'CL_TotalOwed' field.
   */
  public java.lang.Double getCLTotalOwed() {
    return CL_TotalOwed;
  }

  /**
   * Sets the value of the 'CL_TotalOwed' field.
   * @param value the value to set.
   */
  public void setCLTotalOwed(java.lang.Double value) {
    this.CL_TotalOwed = value;
  }

  /**
   * Gets the value of the 'CL_Paid' field.
   * @return The value of the 'CL_Paid' field.
   */
  public java.lang.Boolean getCLPaid() {
    return CL_Paid;
  }

  /**
   * Sets the value of the 'CL_Paid' field.
   * @param value the value to set.
   */
  public void setCLPaid(java.lang.Boolean value) {
    this.CL_Paid = value;
  }

  /**
   * Gets the value of the 'CS_Description' field.
   * @return The value of the 'CS_Description' field.
   */
  public java.lang.CharSequence getCSDescription() {
    return CS_Description;
  }

  /**
   * Sets the value of the 'CS_Description' field.
   * @param value the value to set.
   */
  public void setCSDescription(java.lang.CharSequence value) {
    this.CS_Description = value;
  }

  /**
   * Gets the value of the 'CL_ProcessDate' field.
   * @return The value of the 'CL_ProcessDate' field.
   */
  public java.lang.Integer getCLProcessDate() {
    return CL_ProcessDate;
  }

  /**
   * Sets the value of the 'CL_ProcessDate' field.
   * @param value the value to set.
   */
  public void setCLProcessDate(java.lang.Integer value) {
    this.CL_ProcessDate = value;
  }

  /**
   * Gets the value of the 'CB_ClaimStateID' field.
   * @return The value of the 'CB_ClaimStateID' field.
   */
  public java.lang.Integer getCBClaimStateID() {
    return CB_ClaimStateID;
  }

  /**
   * Sets the value of the 'CB_ClaimStateID' field.
   * @param value the value to set.
   */
  public void setCBClaimStateID(java.lang.Integer value) {
    this.CB_ClaimStateID = value;
  }

  /**
   * Creates a new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder.
   * @return A new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder
   */
  public static org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder newBuilder() {
    return new org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder();
  }

  /**
   * Creates a new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder
   */
  public static org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder newBuilder(org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder other) {
    return new org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder(other);
  }

  /**
   * Creates a new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder by copying an existing Claim_ClaimStatus_ClaimStatusClaimLink instance.
   * @param other The existing instance to copy.
   * @return A new Claim_ClaimStatus_ClaimStatusClaimLink RecordBuilder
   */
  public static org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder newBuilder(org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink other) {
    return new org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder(other);
  }

  /**
   * RecordBuilder for Claim_ClaimStatus_ClaimStatusClaimLink instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Claim_ClaimStatus_ClaimStatusClaimLink>
    implements org.apache.avro.data.RecordBuilder<Claim_ClaimStatus_ClaimStatusClaimLink> {

    private int CL_ClaimID;
    private java.lang.Double CL_FeeSubmitted;
    private java.lang.Double CL_TotalOwed;
    private boolean CL_Paid;
    private java.lang.CharSequence CS_Description;
    private int CL_ProcessDate;
    private java.lang.Integer CB_ClaimStateID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[0].schema(), other.CL_ClaimID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CL_FeeSubmitted)) {
        this.CL_FeeSubmitted = data().deepCopy(fields()[1].schema(), other.CL_FeeSubmitted);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CL_TotalOwed)) {
        this.CL_TotalOwed = data().deepCopy(fields()[2].schema(), other.CL_TotalOwed);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CL_Paid)) {
        this.CL_Paid = data().deepCopy(fields()[3].schema(), other.CL_Paid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[4].schema(), other.CS_Description);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CL_ProcessDate)) {
        this.CL_ProcessDate = data().deepCopy(fields()[5].schema(), other.CL_ProcessDate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CB_ClaimStateID)) {
        this.CB_ClaimStateID = data().deepCopy(fields()[6].schema(), other.CB_ClaimStateID);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Claim_ClaimStatus_ClaimStatusClaimLink instance
     * @param other The existing instance to copy.
     */
    private Builder(org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CL_ClaimID)) {
        this.CL_ClaimID = data().deepCopy(fields()[0].schema(), other.CL_ClaimID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CL_FeeSubmitted)) {
        this.CL_FeeSubmitted = data().deepCopy(fields()[1].schema(), other.CL_FeeSubmitted);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CL_TotalOwed)) {
        this.CL_TotalOwed = data().deepCopy(fields()[2].schema(), other.CL_TotalOwed);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CL_Paid)) {
        this.CL_Paid = data().deepCopy(fields()[3].schema(), other.CL_Paid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[4].schema(), other.CS_Description);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CL_ProcessDate)) {
        this.CL_ProcessDate = data().deepCopy(fields()[5].schema(), other.CL_ProcessDate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CB_ClaimStateID)) {
        this.CB_ClaimStateID = data().deepCopy(fields()[6].schema(), other.CB_ClaimStateID);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'CL_ClaimID' field.
      * @return The value.
      */
    public java.lang.Integer getCLClaimID() {
      return CL_ClaimID;
    }

    /**
      * Sets the value of the 'CL_ClaimID' field.
      * @param value The value of 'CL_ClaimID'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCLClaimID(int value) {
      validate(fields()[0], value);
      this.CL_ClaimID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_ClaimID' field has been set.
      * @return True if the 'CL_ClaimID' field has been set, false otherwise.
      */
    public boolean hasCLClaimID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CL_ClaimID' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCLClaimID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CL_FeeSubmitted' field.
      * @return The value.
      */
    public java.lang.Double getCLFeeSubmitted() {
      return CL_FeeSubmitted;
    }

    /**
      * Sets the value of the 'CL_FeeSubmitted' field.
      * @param value The value of 'CL_FeeSubmitted'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCLFeeSubmitted(java.lang.Double value) {
      validate(fields()[1], value);
      this.CL_FeeSubmitted = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_FeeSubmitted' field has been set.
      * @return True if the 'CL_FeeSubmitted' field has been set, false otherwise.
      */
    public boolean hasCLFeeSubmitted() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CL_FeeSubmitted' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCLFeeSubmitted() {
      CL_FeeSubmitted = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'CL_TotalOwed' field.
      * @return The value.
      */
    public java.lang.Double getCLTotalOwed() {
      return CL_TotalOwed;
    }

    /**
      * Sets the value of the 'CL_TotalOwed' field.
      * @param value The value of 'CL_TotalOwed'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCLTotalOwed(java.lang.Double value) {
      validate(fields()[2], value);
      this.CL_TotalOwed = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_TotalOwed' field has been set.
      * @return True if the 'CL_TotalOwed' field has been set, false otherwise.
      */
    public boolean hasCLTotalOwed() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'CL_TotalOwed' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCLTotalOwed() {
      CL_TotalOwed = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CL_Paid' field.
      * @return The value.
      */
    public java.lang.Boolean getCLPaid() {
      return CL_Paid;
    }

    /**
      * Sets the value of the 'CL_Paid' field.
      * @param value The value of 'CL_Paid'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCLPaid(boolean value) {
      validate(fields()[3], value);
      this.CL_Paid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_Paid' field has been set.
      * @return True if the 'CL_Paid' field has been set, false otherwise.
      */
    public boolean hasCLPaid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CL_Paid' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCLPaid() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CS_Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getCSDescription() {
      return CS_Description;
    }

    /**
      * Sets the value of the 'CS_Description' field.
      * @param value The value of 'CS_Description'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCSDescription(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CS_Description = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CS_Description' field has been set.
      * @return True if the 'CS_Description' field has been set, false otherwise.
      */
    public boolean hasCSDescription() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CS_Description' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCSDescription() {
      CS_Description = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'CL_ProcessDate' field.
      * @return The value.
      */
    public java.lang.Integer getCLProcessDate() {
      return CL_ProcessDate;
    }

    /**
      * Sets the value of the 'CL_ProcessDate' field.
      * @param value The value of 'CL_ProcessDate'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCLProcessDate(int value) {
      validate(fields()[5], value);
      this.CL_ProcessDate = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'CL_ProcessDate' field has been set.
      * @return True if the 'CL_ProcessDate' field has been set, false otherwise.
      */
    public boolean hasCLProcessDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'CL_ProcessDate' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCLProcessDate() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'CB_ClaimStateID' field.
      * @return The value.
      */
    public java.lang.Integer getCBClaimStateID() {
      return CB_ClaimStateID;
    }

    /**
      * Sets the value of the 'CB_ClaimStateID' field.
      * @param value The value of 'CB_ClaimStateID'.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder setCBClaimStateID(java.lang.Integer value) {
      validate(fields()[6], value);
      this.CB_ClaimStateID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'CB_ClaimStateID' field has been set.
      * @return True if the 'CB_ClaimStateID' field has been set, false otherwise.
      */
    public boolean hasCBClaimStateID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'CB_ClaimStateID' field.
      * @return This builder.
      */
    public org.gms.claimclasses.Claim_ClaimStatus_ClaimStatusClaimLink.Builder clearCBClaimStateID() {
      CB_ClaimStateID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Claim_ClaimStatus_ClaimStatusClaimLink build() {
      try {
        Claim_ClaimStatus_ClaimStatusClaimLink record = new Claim_ClaimStatus_ClaimStatusClaimLink();
        record.CL_ClaimID = fieldSetFlags()[0] ? this.CL_ClaimID : (java.lang.Integer) defaultValue(fields()[0]);
        record.CL_FeeSubmitted = fieldSetFlags()[1] ? this.CL_FeeSubmitted : (java.lang.Double) defaultValue(fields()[1]);
        record.CL_TotalOwed = fieldSetFlags()[2] ? this.CL_TotalOwed : (java.lang.Double) defaultValue(fields()[2]);
        record.CL_Paid = fieldSetFlags()[3] ? this.CL_Paid : (java.lang.Boolean) defaultValue(fields()[3]);
        record.CS_Description = fieldSetFlags()[4] ? this.CS_Description : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.CL_ProcessDate = fieldSetFlags()[5] ? this.CL_ProcessDate : (java.lang.Integer) defaultValue(fields()[5]);
        record.CB_ClaimStateID = fieldSetFlags()[6] ? this.CB_ClaimStateID : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Claim_ClaimStatus_ClaimStatusClaimLink>
    WRITER$ = (org.apache.avro.io.DatumWriter<Claim_ClaimStatus_ClaimStatusClaimLink>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Claim_ClaimStatus_ClaimStatusClaimLink>
    READER$ = (org.apache.avro.io.DatumReader<Claim_ClaimStatus_ClaimStatusClaimLink>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
